import JSZip from "jszip";
import { saveAs } from "file-saver";

export interface ScormConfig {
    courseTitle: string;
    identifier: string;
    organization: string;
    itemTitle: string;
    htmlContent: string; // The content of index.html
    htmlFileName?: string; // e.g. "index.html"
}

export const generateManifest = (config: ScormConfig) => {
    const { courseTitle, identifier, organization, itemTitle, htmlFileName = "index.html" } = config;

    // Sanitize identifier to be safe for XML
    const safeIdentifier = identifier.replace(/[^a-zA-Z0-9_]/g, "_");
    const safeOrg = organization.replace(/[^a-zA-Z0-9_]/g, "_");

    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  SCORM 1.2 Manifest File
  Generated by SCORM Generator
-->
<manifest identifier="${safeIdentifier}" version="1.1"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.imsproject.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p1p2 adlcp_rootv1p1p2.xsd">

  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>

  <organizations default="${safeOrg}">
    <organization identifier="${safeOrg}">
      <title>${courseTitle}</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>${itemTitle}</title>
      </item>
    </organization>
  </organizations>

  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormtype="sco" href="${htmlFileName}">
      <file href="${htmlFileName}"/>
    </resource>
  </resources>
</manifest>`;
};

export const generateScormPackage = async (config: ScormConfig) => {
    const zip = new JSZip();

    // Add imsmanifest.xml
    const manifest = generateManifest(config);
    zip.file("imsmanifest.xml", manifest);

    // Add index.html
    // We assume htmlContent is the text content of the file. 
    // If the user uploaded a file, we should have read it as text or ArrayBuffer.
    // The interface accepts string for simplicity but we might want to support Blob/ArrayBuffer if the file has images embedded or is large.
    // For single file web app, string is usually fine.
    // But wait, if the user uploads a zip or an html with assets, we only support single file text?
    // The prompt says "single file web app html code", so string is fine.
    const fileName = config.htmlFileName || "index.html";
    zip.file(fileName, config.htmlContent);

    // Generate zip blob
    const content = await zip.generateAsync({ type: "blob" });

    // Save file
    saveAs(content, `${config.identifier || "scorm-package"}.zip`);
};
